"""
Django settings for codebase project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import configparser
import os
from pathlib import Path

import dj_database_url
import sentry_sdk
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
from loguru import logger
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration

conf_parser = configparser.ConfigParser()
conf_parser.read(os.getenv("CONFIG_FILE", "config.ini"))
file_config = conf_parser["DEFAULT"]

load_dotenv()


def get_config(name, default=None):
    # Get the value from the config file, or the environment variable, or the default value
    return file_config.get(name, os.getenv(name, default))


def _parse_sentinel_host_port(server_str):
    """Parse 'host:port' or 'host' into (host, port) tuple."""
    server_str = server_str.lstrip(":")
    if ":" in server_str:
        host, port = server_str.rsplit(":", 1)
        return (host, int(port))
    return (server_str, 26379)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = file_config.get(
    "SECRET_KEY",
    os.getenv(
        "SECRET_KEY",
        "django-insecure-x*25w(mnxs5#piap8=mje^fn6&wr+0ry_6up!h45h&8puthi$-",
    ),
)

# SECURITY WARNING: don't run with debug turned on in production!
env = os.getenv("GITLAB_ENVIRONMENT_NAME", "production")
DEV = False
DEBUG = False
if env == "debug":
    DEBUG = True
elif env =="dev":
    DEV = True

ALLOWED_HOSTS = ["*"]

APP_RELEASE_VERSION = get_config("APP_RELEASE_VERSION", "0.1.0")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sites",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "whitenoise.runserver_nostatic",
    # Third-party apps
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "django_filters",
    "rest_framework",
    # local
    "app",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django_currentuser.middleware.ThreadLocalUserMiddleware",
]

ROOT_URLCONF = "codebase.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "codebase.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = get_config("DATABASE_URL", f"sqlite:///{BASE_DIR}/db.sqlite3")

db_config = dj_database_url.parse(DATABASE_URL)
db_config.update({"DISABLE_SERVER_SIDE_CURSORS": True})
DATABASES = {"default": db_config}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "vi"

TIME_ZONE = "Asia/Ho_Chi_Minh"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

redis_url = get_config(
    "REDIS_URL",
    f"redis://:{get_config('REDIS_PASSWD', '')}@{get_config('REDIS_HOST', 'localhost')}/0",
)

# celery config
CELERY_BROKER_URL = redis_url
CELERY_RESULT_BACKEND = redis_url
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        },
    },
}

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Configure the Sentry SDK
# https://docs.sentry.io/platforms/python/guides/django/#configure
sentry_url = get_config("SENTRY_DSN", os.getenv("SENTRY_DSN", ""))
sentry_sdk.init(
    dsn=sentry_url,
    integrations=[DjangoIntegration(), CeleryIntegration()],
    traces_sample_rate=1.0,
    profiles_sample_rate=1.0,
    send_default_pii=True,
)

# Configure Django REST framework
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": int(get_config("API_PAGE_SIZE", 10)),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FileUploadParser",
        "rest_framework.parsers.FormParser",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework.authentication.SessionAuthentication",),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
}

# Django CORS Headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "xsrfheadername",
    "xsrfcookiename",
    "content-type",
    "x-csrftoken",
    "csrftoken",
    "x-timezone",
    "X-CSRFToken"
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # Vue dev
    "http://localhost:5173",  # Vite default
    "http://localhost:3000",  # Nuxt default
]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be sent


SESSION_COOKIE_AGE = get_config("SESSION_COOKIE_AGE", 2592000)  # (4 weeks, in seconds)
# todo: update CSRF_TRUSTED_ORIGINS when deploy to others domain
CSRF_COOKIE_NAME = "codebase_csrftoken"
CSRF_TRUSTED_ORIGINS = get_config(
    "CSRF_TRUSTED_ORIGINS",
    [
        "http://localhost:8000",
        "http://localhost:3000",
    ],
)

if isinstance(CSRF_TRUSTED_ORIGINS, str):
    CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS.split(",")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", get_config("HTTP_X_FORWARDED_PROTO", "https"))


AWS_S3_ACCESS_KEY_ID = get_config("AWS_S3_ACCESS_KEY_ID")
AWS_S3_SECRET_ACCESS_KEY = get_config("AWS_S3_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = get_config("AWS_STORAGE_BUCKET_NAME")
AWS_S3_ENDPOINT_URL = get_config("AWS_S3_ENDPOINT_URL")

if AWS_S3_ACCESS_KEY_ID:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
    }


# Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587

EMAIL_HOST_USER = get_config("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_config("EMAIL_HOST_PASSWORD", "")

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SECRET_KEY_GG = get_config("SECRET_KEY_GG")
CLIENT_ID_GG = get_config("CLIENT_ID_GG")

MENU_MAX_DEPTH = int(get_config("MENU_MAX_DEPTH", 3))

# When running in debug mode, add the debug toolbar
if DEBUG:
    DEBUG_AUTO_LOGIN_EMAIL = get_config("DEBUG_AUTO_LOGIN_EMAIL", None)
    DEBUG_DISABLE_CSRF = get_config("DEBUG_DISABLE_CSRF", False)
    logger.debug(f"DEBUG_AUTO_LOGIN_EMAIL: {DEBUG_AUTO_LOGIN_EMAIL}")

    # If DEBUG, this setting defaults to allowing unrestricted access:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = (
        "accounts.auth.CsrfExemptSessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    )
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    )

    CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins

    # CSRF
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://localhost:3000",
        "http://localhost:8000",
    ]

    # Session & CSRF cookies do not need to be secure in development
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # SSL Header configuration
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        None,
    )  # No need to configure in development

    # Development-only apps
    INSTALLED_APPS = [
        *INSTALLED_APPS,
        "debug_toolbar",
        # "silk",
    ]

    # Development-only middleware
    MIDDLEWARE = [
        *MIDDLEWARE,
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        "accounts.middleware.CustomCsrfMiddleware",
        "accounts.middleware.DebugAutoLoginMiddleware",
        # "silk.middleware.SilkyMiddleware",
    ]

    TEMPLATES[0]["OPTIONS"]["context_processors"].insert(
        0, "django.template.context_processors.debug"
    )

    INTERNAL_IPS = [
        "localhost",
        "127.0.0.1",
    ]

elif DEV:
    DEBUG_DISABLE_CSRF = get_config("DEBUG_DISABLE_CSRF", False)

    # If DEBUG, this setting defaults to allowing unrestricted access:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"] = (
        "accounts.auth.CsrfExemptSessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    )
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = (
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    )

    CORS_ALLOW_ALL_ORIGINS = True

    # CSRF
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://localhost:3000",
        "http://localhost:8000",
    ]

    # Session & CSRF cookies do not need to be secure in development
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # SSL Header configuration
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        None,
    )  # No need to configure in development

    # Development-only apps
    INSTALLED_APPS = [
        *INSTALLED_APPS,
        "debug_toolbar",
        # "silk",
    ]

    # Development-only middleware
    MIDDLEWARE = [
        *MIDDLEWARE,
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        "accounts.middleware.CustomCsrfMiddleware",
        # "silk.middleware.SilkyMiddleware",
    ]

    TEMPLATES[0]["OPTIONS"]["context_processors"].insert(
        0, "django.template.context_processors.debug"
    )

    INTERNAL_IPS = [
        "localhost",
        "127.0.0.1",
    ]
