# Generated by Django 5.2.10 on 2026-07-31 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_fb_id', models.CharField(help_text='ID của Fanpage trên Facebook.', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Tên Fanpage.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản ghi.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật gần nhất.')),
            ],
            options={
                'verbose_name': 'Fanpage',
                'verbose_name_plural': 'Fanpage',
            },
        ),
        migrations.CreateModel(
            name='SpamWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Từ khóa hoặc cụm từ cần lọc.', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản ghi.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật gần nhất.')),
            ],
            options={
                'verbose_name': 'Từ khóa spam',
                'verbose_name_plural': 'Từ khóa spam',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Tên người dùng Facebook.', max_length=255)),
                ('access_token', models.TextField(help_text='User Access Token của Facebook.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản ghi.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật gần nhất.')),
            ],
            options={
                'verbose_name': 'User Token',
                'verbose_name_plural': 'User Token',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_fb_id', models.CharField(help_text='ID bài viết trên Facebook.', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Nội dung hoặc tiêu đề bài viết.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản ghi.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật gần nhất.')),
                ('page', models.ForeignKey(help_text='Fanpage chứa bài viết.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.page')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_fb_id', models.CharField(help_text='ID bình luận trên Facebook.', max_length=100, unique=True)),
                ('title', models.TextField(help_text='Nội dung bình luận.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản ghi.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật gần nhất.')),
                ('post', models.ForeignKey(help_text='Bài viết chứa bình luận.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
            },
        ),
        migrations.CreateModel(
            name='PageToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Page Access Token của Facebook.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Thời điểm hết hạn của Page Token. Để trống nếu token không có thời hạn hoặc không xác định.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tạo bản ghi.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời điểm cập nhật gần nhất.')),
                ('page', models.ForeignKey(help_text='Fanpage sử dụng Page Token này.', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='app.page')),
                ('user_token', models.ForeignKey(help_text='User Token sở hữu Page Token này.', on_delete=django.db.models.deletion.CASCADE, related_name='page_tokens', to='app.usertoken')),
            ],
            options={
                'verbose_name': 'Page Token',
                'verbose_name_plural': 'Page Token',
            },
        ),
    ]
