# Generated by Django 5.2.10 on 2026-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('delete', 'Xóa'), ('hide', 'Ẩn')], help_text='Hành động đã thực hiện trên bình luận: xóa hay ẩn.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(help_text='Nội dung bài viết.'),
        ),
    ]
