# Generated by Django 5.2.10 on 2026-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_status_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.JSONField(blank=True, help_text='Dữ liệu JSON thô của bình luận từ Facebook Graph API.', null=True),
        ),
    ]
