# Generated by Django 5.2.10 on 2026-08-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Tài khoản ứng dụng', 'verbose_name_plural': 'Tài khoản ứng dụng'},
        ),
    ]
